### ISSUE TITLE
When clicking on an image the timeline resets to the top

### ISSUE THREAD

**Issue by SHOWTEX** [furyutei/twOpenOriginalImage#17] opened 2020-12-19 12:56 UTC
Seems like its a new issue, havent had this before.

**Comment by yms0719** [comment] 2020-12-19 16:40
I am having the same issue. It worked just fine days ago.

**Comment by furyutei** [comment] 2020-12-20 04:26
The problem was caused by a change in Twitter's behavior.
It should be fixed in [version 0.1.8.1401](https://github.com/furyutei/twOpenOriginalImage/commit/aac12327eca004ae9d3b584cee8cf8530f22e4ee).

**Closed** 2020-12-20 04:34 UTC
